version: '3'

services:
  go_ecommerce_app:
    build:
      context: .
      dockerfile: docker/Dockerfile-golang
    container_name: go_ecommerce_app
    working_dir: /app
    volumes:
      - .:/app
  go_ecommerce_service:
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
    container_name: go_ecommerce_service
    working_dir: /app
    ports:
      - "8098:80"
    volumes:
      - ./:/app
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
networks:
  default:
    external:
      name: local_network
